### ISSUE TITLE
Update HPC0

### ISSUE THREAD

**Issue by agdturner** [ARCTraining/rc-slides#11]
Update slides following latest run of the course. There are a few tweaks and additions that are wanted...

**Comment by agdturner** [comment]
I think there are still some things that should be done: We should maybe:
1. fork the shell-training repository and use the fork
2. add an example solution to the filtering using grep to introduce that
3. add an example search and replace using sed to introduce that better
4. link to the team page on the website or pull in information from there rather than having to update team information in many places

**Comment by jhodrien** [comment]
Yes, yes, yes.  Perhaps think about what order to put them in - sed likely last, perhaps grep before for loops?  Need to plan for not finishing all the material.

All the team info is pulled in from the variable file, so it is at least a single place for all training courses.

**Comment by agdturner** [comment]
The repository is already forked and available here: https://github.com/ARCTraining/shell-training

**Comment by jhodrien** [comment]
Yes, I think I was half way through unpicking things.
