### ISSUE TITLE
Update Theme

### ISSUE THREAD

**Issue by patricia-ternes** [ARCTraining/rc-slides#17]
# Theme Update

After we fix #16 the next step is apply the same Theme to all slides and verify if everything is working as expected:

- [ ] hpc0.qmd
- [ ] template.qmd
- [ ] index.qmd (?)

## HPC0 Theme update

- Verify how every slides render with the new theme and tweak as necessary

## Index

In my test, I found a possible problem with the index page.
I am not sure, but it seems that install a new theme may affect this page.

One possible solution if this happens is:

```
format:
  html:
    embed-resources: true
```

**Comment by jhodrien** [comment]
Nearly there now, but I'll submit another PR to fix the odd slide that's still formatted a bit oddly.

**Comment by patricia-ternes** [comment]
I will list here the pages look oddly to me

**Comment by patricia-ternes** [comment]
- [ ] Title image (I will fix this >> just writing down to not forgot)
- [ ] Navigation arrow overlapping with the page numbers (change in all files)
- [ ] Slide 18: minor >> command breaking between lines (we can leave it)
- [ ] Slide 21: Text is overlapping with the footer. (this is the only one really problematic)
- [ ] Slide 23: 1 & 2 are rendered differently (we can leave it)
