### ISSUE TITLE
HPC0 fixes following November 2023 session

### ISSUE THREAD

**Issue by jhodrien** [ARCTraining/rc-slides#28]
pwd is a bad example of a command to use --help with, as it's a shell built in, and doesn't work on arc4.  Should use `ls --help` instead?

**Comment by jhodrien** [comment]
-H on the ls page should be -h for human readable

**Comment by jhodrien** [comment]
Would it be a good idea to push the .bash* files later on, so we've already covered the use of the bash history before we see them?

**Comment by Tian1Pan** [comment]
Issue fixed with PR #29
